### ISSUE TITLE
go build

### ISSUE THREAD

**Issue by Gavidw** [trezor/blockbook#718]
bchain/coins/blockchain.go:28:2: //go:build comment without // +build comment

**Comment by Gavidw** [comment]
go build -tags 'rocksdb_6_16'

blockbook.go:22:2: //go:build comment without // +build comment
api/types.go:10:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:14:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:15:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:16:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:17:2: //go:build comment without // +build comment
bchain/coins/bch/bcashparser.go:12:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:19:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:21:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:22:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:23:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:24:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:25:2: //go:build comment without // +build comment
bchain/coins/blockchain.go:26:2: //go:build comment without // +build comment
api/types.go:11:2: //go:build comment without // +build comment

**Comment by martinboehm** [comment]
Hi, you need go1.17

**Comment by Gavidw** [comment]
A new error occurred after I updated to 1.17

# github.com/flier/gorocksdb
/root/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/array.go:4:11: fatal error: rocksdb/c.h: No such file or directory
 // #include "rocksdb/c.h"
           ^~~~~~~~~~~~~
compilation terminated.

**Comment by Gavidw** [comment]
I searched the entire rocksdb file and found a C.H file with the path rocksdb / include / rocksdb / c. H, how should I deal with this problem?

**Comment by Gavidw** [comment]
New error:
# runtime/cgo
/usr/bin/ld: cannot find -lrocksdb
collect2: error: ld returned 1 exit status

**Comment by martinboehm** [comment]
Did you follow the https://github.com/trezor/blockbook/blob/master/docs/build.md#manual-build procedure, especially the part about RocksDB?

**Comment by Gavidw** [comment]
Yes, I confirm that RocksDB is installed according to the document, and the output of the last step is shown in the attachment.

**Comment by Gavidw** [comment]
![222](https://user-images.githubusercontent.com/32816662/146733463-a1eaa60d-6d2b-4e00-8af2-3a7ddbd27425.png)
go build  -tags rocksdb_6_16   another error
# github.com/flier/gorocksdb
../go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/array.go:4:11: fatal error: rocksdb/c.h: No such file or directory
 // #include "rocksdb/c.h"
           ^~~~~~~~~~~~~

**Comment by martinboehm** [comment]
It seems to me that this
```
export CGO_CFLAGS="-I/path/to/rocksdb/include"
export CGO_LDFLAGS="-L/path/to/rocksdb -lrocksdb -lstdc++ -lm -lz -ldl -lbz2 -lsnappy -llz4"
```
is not set correctly.

**Comment by Gavidw** [comment]
I have executed this order, but he still reports an error:
/usr/bin/ld: cannot find -lrocksdb
collect2: error: ld returned 1 exit status

**Comment by martinboehm** [comment]
Sorry, I cannot help you to debug your local environment. Try to figure out the issue why the linker cannot find rocskdb. Maybe this https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary could help you.

**Comment by marekyggdrasil** [comment]
On a fresh server I followed https://github.com/trezor/blockbook/blob/master/docs/build.md#manual-build strictly and getting this

```
$ go build -tags rocksdb_6_16
# github.com/flier/gorocksdb
../../pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/array.go:4:11: fatal error: rocksdb/c.h: No such file or directory
    4 | // #include "rocksdb/c.h"
      |           ^~~~~~~~~~~~~
compilation terminated.
```

I think something is missing in your docs. Also, the `apt` command is missing `libtool`.

**Comment by marekyggdrasil** [comment]
Ok I found what was the problem for me, here's my PR to your build instructions https://github.com/trezor/blockbook/pull/804
